### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by oe3jtb** [fcatt/chirp-flatpak-uvk5#1]
Hi , I am just curious, I am using the module parameter for loading the py file
"C:\Program Files (x86)\CHIRP\chirpwx.exe" --module C:\Users\Alex\Desktop\Quansheng\uvk5_egzumer_f4hwn_ver_3_1_0.py
What i the advantage of the flatpack
tnx kind regards

**Comment by fcatt** [comment]
Hi, I couldn't find a  flatpak for the latest version of CHIRP-Next so I created it, and as I own a UV-K5 I integrated the driver from @armel. I see you're using Windows, so a flatpak probably won't be of any use to you, it is a way of packaging and running software for Linux-based distributions.

**Comment by oe3jtb** [comment]
ah ok that was the reason tnc for the fast answer 73 and kind regards Alex
